name: 回报错误
description: 在使用 粉丝牌助手 的过程中遇到了错误
title: "[Bug]: "
labels: ["bug?"]

body:
    # User's README and agreement
    - type: markdown
      attributes:
          value: |
              ## 感谢您愿意填写错误回报！
              ## 以下是一些注意事项，请务必阅读让我们能够更容易处理

              ### ❗ | 确定没有相同问题的ISSUE已被提出. 
              ### 🌎| 请准确填写环境信息
              ### ❔ | 提供出现问题前后至少 10 秒的完整日志内容。请自行删除日志内存在的个人信息及敏感内容。

              ## 如果您不知道如何有效、精准地表述，我们建议您先阅读《提问的智慧》
              链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
              ---
    - type: checkboxes
      id: terms
      attributes:
          label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
          options:
              - label: '我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)'
                required: true
              - label: "我已经在 [Issue Tracker](https://github.com/XiaoMiku01/fansMedalHelper/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。"
                required: true
              - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
                required: true

    # User's data
    - type: markdown
      attributes:
          value: |
              ## 环境信息
              请根据实际使用环境修改以下信息。
    - type: input
      id: env-ver
      attributes:
          label: 粉丝牌助手 版本
      validations:
          required: true

    # Env | VM Version
    - type: dropdown
      id: env-vm-ver
      attributes:
          label: 运行环境
          description: 选择运行 粉丝牌助手 的系统版本
          options:
              - Windows (64)
              - Windows (32/x84)
              - MacOS
              - Linux (云函数)
              - Ubuntu
              - CentOS
              - ArchLinux
              - UNIX (Android)
              - 其它（请在下方说明）
      validations:
          required: true

    # Env | VM Arch
    - type: dropdown
      id: env-vm-arch
      attributes:
          label: 运行架构
          description: (可选) 选择运行 粉丝牌助手 的系统架构
          options:
              - AMD64
              - x86
              - ARM [32] (别名：AArch32 / ARMv7）
              - ARM [64] (别名：AArch64 / ARMv8）
              - 其它

    # Env | Connection type
    - type: dropdown
      id: env-conn-type
      attributes:
          label: 部署方式
          description: 粉丝牌助手 的部署方式
          options:
              - 阿里云函数
              - 腾讯云函数
              - 本地
              - 其它（请在下方说明）
      validations:
          required: true   
          
    - type: input
      id: num
      attributes:
          label: 粉丝牌数量
      validations:
          required: true 
    # Optional | Logging
    - type: textarea
      id: logging
      attributes:
          label: 日志记录（可选）
          render: python

    # Optional | Extra description
    - type: textarea
      id: extra-desc
      attributes:
          label: 补充说明（可选）
